package com.dzikoysk.sqiffy.dsl.statements

import com.dzikoysk.sqiffy.SqiffyDatabase
import com.dzikoysk.sqiffy.definition.DataType.SERIAL
import com.dzikoysk.sqiffy.dsl.Row
import com.dzikoysk.sqiffy.dsl.Statement
import com.dzikoysk.sqiffy.dsl.Table
import com.dzikoysk.sqiffy.dsl.Values
import com.dzikoysk.sqiffy.dsl.generator.ParameterAllocator
import com.dzikoysk.sqiffy.dsl.generator.bindArguments
import com.dzikoysk.sqiffy.dsl.generator.toQueryColumn
import org.slf4j.event.Level

open class AbstractInsertStatement(
    protected val database: SqiffyDatabase,
    protected val table: Table,
    protected val values: Values
) : Statement {

    protected val autogeneratedKey = table
        .getColumns()
        .firstOrNull { it.dataType == SERIAL }

    protected open fun <T> map(mapper: (Row) -> T): List<T> {
        return database.getJdbi().withHandle<List<T>, Exception> { handle ->
            val allocator = ParameterAllocator()

            val (query, args) = database.sqlQueryGenerator.createInsertQuery(
                allocator = allocator,
                tableName = table.getName(),
                columns = values.getColumns().map { it.toQueryColumn() }
            )

            database.logger.log(Level.DEBUG, "Executing query: $query with arguments: $args")

            handle
                .createUpdate(query)
                .bindArguments(args, values)
                .executeAndReturnGeneratedKeys()
                .map { view -> mapper(Row(
                    view = view,
                    autogeneratedKey = autogeneratedKey
                )) }
                .list()
        }
    }

}

open class InsertStatement(
    database: SqiffyDatabase,
    table: Table,
    values: Values
) : AbstractInsertStatement(database, table, values) {

    fun execute(): Unit =
        map { }.firstOrNull() ?: Unit

}

open class AutogeneratedKeyInsertStatement(
    database: SqiffyDatabase,
    table: Table,
    values: Values
) : AbstractInsertStatement(database, table, values) {

    public override fun <T> map(mapper: (Row) -> T): List<T> =
        super.map(mapper)

}