package com.dzikoysk.sqiffy.specification

import com.dzikoysk.sqiffy.definition.DataType.BOOLEAN
import com.dzikoysk.sqiffy.definition.DataType.DATE
import com.dzikoysk.sqiffy.definition.DataType.DATETIME
import com.dzikoysk.sqiffy.definition.DataType.DOUBLE
import com.dzikoysk.sqiffy.definition.DataType.ENUM
import com.dzikoysk.sqiffy.definition.DataType.INT
import com.dzikoysk.sqiffy.definition.DataType.LONG
import com.dzikoysk.sqiffy.definition.DataType.SERIAL
import com.dzikoysk.sqiffy.definition.DataType.TIMESTAMP
import com.dzikoysk.sqiffy.definition.DataType.VARCHAR
import com.dzikoysk.sqiffy.definition.Definition
import com.dzikoysk.sqiffy.definition.DefinitionVersion
import com.dzikoysk.sqiffy.definition.EnumDefinition
import com.dzikoysk.sqiffy.definition.EnumOperation.ADD_VALUES
import com.dzikoysk.sqiffy.definition.EnumVersion
import com.dzikoysk.sqiffy.definition.Property

/** A table covering every supported column type, used to verify type round-trips. */
@Definition(
    versions = [
        DefinitionVersion(
            version = "1.0.0",
            name = "types",
            properties = [
                Property(name = "id", type = SERIAL),
                Property(name = "label", type = VARCHAR, details = "64"),
                Property(name = "amount", type = INT),
                Property(name = "counter", type = LONG),
                Property(name = "ratio", type = DOUBLE),
                Property(name = "flag", type = BOOLEAN),
                Property(name = "day", type = DATE),
                Property(name = "moment", type = DATETIME),
                Property(name = "instant", type = TIMESTAMP),
            ]
        )
    ]
)
internal object TypesDefinition

/** A table without an autogenerated key. */
@Definition(
    versions = [
        DefinitionVersion(
            version = "1.0.0",
            name = "links",
            properties = [
                Property(name = "alpha", type = INT),
                Property(name = "beta", type = INT),
            ]
        )
    ]
)
internal object LinkDefinition

interface HasLabel {
    val label: String
}

/** A hand-written enum already on the classpath — referenced via [PriorityDefinition], never generated. */
enum class Priority {
    LOW, HIGH
}

/** Maps the `priority` column onto the existing [Priority] enum (validated against [Priority]'s constants). */
@EnumDefinition(
    name = "priority",
    mappedFrom = Priority::class,
    value = [EnumVersion(version = "1.0.0", operation = ADD_VALUES, values = ["LOW", "HIGH"])]
)
internal object PriorityDefinition

/**
 * A table whose generated entity implements a user-provided interface and maps an enum column onto an
 * existing (`mappedFrom`) enum.
 */
@Definition(
    implements = [HasLabel::class],
    versions = [
        DefinitionVersion(
            version = "1.0.0",
            name = "tagged",
            properties = [
                Property(name = "id", type = SERIAL),
                Property(name = "label", type = VARCHAR, details = "32"),
                Property(name = "priority", type = ENUM, enumDefinition = PriorityDefinition::class, nullable = true),
            ]
        )
    ]
)
internal object TaggedDefinition
