package com.dzikoysk.sqiffy.migrator

import com.dzikoysk.sqiffy.SqiffyDatabase
import com.dzikoysk.sqiffy.changelog.Enums
import com.dzikoysk.sqiffy.dsl.Values
import com.dzikoysk.sqiffy.dsl.generator.ParameterAllocator
import com.dzikoysk.sqiffy.dsl.generator.bindArguments
import com.dzikoysk.sqiffy.dsl.generator.toQueryColumn
import org.jdbi.v3.core.Handle

/** Prefix for metadata rows that record an applied file-based changeset, keyed by its resolved path. */
private const val CHANGESET_KEY_PREFIX = "changeset:"

/**
 * Reads and writes the applied-changeset ledger inside the shared [SqiffyMetadataTable].
 *
 * Each applied migration is stored as a single row: `key = "changeset:<resolved path>"`,
 * `value = <sha-256 checksum of the script>`. This namespacing means the file-based migrator and
 * [SqiffyMigrator]'s `version` row can coexist in the same `sqiffy_metadata` table without
 * stepping on each other.
 */
internal class ChangelogLedger(
    private val database: SqiffyDatabase,
    private val metadataTable: SqiffyMetadataTable
) {

    fun ensureTable(handle: Handle) {
        handle.execute(
            database.sqlSchemeGenerator.createTable(
                name = metadataTable.getName(),
                properties = metadataTable.getColumns().map { it.getPropertyData() },
                enums = Enums()
            )
        )
    }

    /** Returns a map of resolved-path -> stored checksum for every changeset already recorded. */
    fun loadApplied(handle: Handle): MutableMap<String, String> {
        val query = database.sqlQueryGenerator.createSelectQuery(
            tableName = metadataTable.getName(),
            selected = listOf(metadataTable.key, metadataTable.value),
        ).query

        val applied = mutableMapOf<String, String>()

        handle.createQuery(query)
            .map { rs, _ -> rs.getString(1) to rs.getString(2) }
            .list()
            .forEach { (key, value) ->
                if (key != null && key.startsWith(CHANGESET_KEY_PREFIX)) {
                    applied[key.removePrefix(CHANGESET_KEY_PREFIX)] = value ?: ""
                }
            }

        return applied
    }

    fun record(handle: Handle, path: String, checksum: String) {
        val allocator = ParameterAllocator()

        val (query, arguments) = database.sqlQueryGenerator.createInsertQuery(
            allocator = allocator,
            tableName = metadataTable.getName(),
            columns = listOf(
                metadataTable.key.toQueryColumn(),
                metadataTable.value.toQueryColumn(),
            ),
            autogeneratedKey = null
        ).updateResult

        val values = Values()
        values[metadataTable.key] = CHANGESET_KEY_PREFIX + path
        values[metadataTable.value] = checksum

        handle.createUpdate(query)
            .bindArguments(arguments, values)
            .execute()
    }

}
