package com.dzikoysk.sqiffy.migrator

import com.dzikoysk.sqiffy.SqiffyDatabase
import com.dzikoysk.sqiffy.changelog.Enums
import com.dzikoysk.sqiffy.dsl.Values
import com.dzikoysk.sqiffy.dsl.like
import com.dzikoysk.sqiffy.dsl.generator.ParameterAllocator
import com.dzikoysk.sqiffy.dsl.generator.bindArguments
import com.dzikoysk.sqiffy.dsl.generator.toQueryColumn
import org.jdbi.v3.core.Handle

private const val CHANGESET_KEY_PREFIX = "changeset:"

/**
 * Applied-changeset history in [SqiffyMetadataTable]: one row per migration
 * (`key = "changeset:<path>"`, `value = <checksum>`), prefixed so it coexists with
 * SqiffyMigrator's `version` row in the same table.
 */
internal class ChangelogHistory(
    private val database: SqiffyDatabase<*>,
    private val metadataTable: SqiffyMetadataTable
) {

    fun ensureTable(handle: Handle) {
        handle.execute(
            database.sqlSchemeGenerator.createTable(
                name = metadataTable.getName(),
                properties = metadataTable.getColumns().map { it.getPropertyData() },
                enums = Enums()
            )
        )
    }

    fun loadApplied(handle: Handle): MutableMap<String, String> {
        val (where, whereArguments) = database.sqlQueryGenerator.createExpression(
            allocator = ParameterAllocator(),
            expression = metadataTable.key like "$CHANGESET_KEY_PREFIX%"
        )

        val query = database.sqlQueryGenerator.createSelectQuery(
            tableName = metadataTable.getName(),
            selected = listOf(metadataTable.key, metadataTable.value),
            where = where,
        ).query

        val applied = mutableMapOf<String, String>()

        handle.createQuery(query)
            .bindArguments(whereArguments)
            .map { rs, _ -> rs.getString(1) to rs.getString(2) }
            .list()
            .forEach { (key, value) ->
                if (key != null) {
                    applied[key.removePrefix(CHANGESET_KEY_PREFIX)] = value ?: ""
                }
            }

        return applied
    }

    fun record(handle: Handle, path: String, checksum: String) {
        val allocator = ParameterAllocator()

        val (query, arguments) = database.sqlQueryGenerator.createInsertQuery(
            allocator = allocator,
            tableName = metadataTable.getName(),
            columns = listOf(
                metadataTable.key.toQueryColumn(),
                metadataTable.value.toQueryColumn(),
            ),
            autogeneratedKey = null
        ).updateResult

        val values = Values()
        values[metadataTable.key] = CHANGESET_KEY_PREFIX + path
        values[metadataTable.value] = checksum

        handle
            .createUpdate(query)
            .bindArguments(arguments, values)
            .execute()
    }

}
