package com.dzikoysk.sqiffy.dsl.generator.dialects

import com.dzikoysk.sqiffy.dsl.generator.ArgumentType.COLUMN
import com.dzikoysk.sqiffy.dsl.generator.Arguments
import com.dzikoysk.sqiffy.dsl.generator.ExpressionColumns
import com.dzikoysk.sqiffy.dsl.generator.ParameterAllocator
import com.dzikoysk.sqiffy.dsl.generator.QueryColumn
import com.dzikoysk.sqiffy.dsl.generator.SqlQueryGenerator.GeneratorResult
import com.dzikoysk.sqiffy.dsl.generator.SqlQueryGenerator.InsertGeneratorResult
import com.dzikoysk.sqiffy.shared.multiline

object PostgreSqlQueryGenerator : GenericQueryGenerator() {

    override fun createInsertQuery(
        allocator: ParameterAllocator,
        tableName: String,
        columns: List<QueryColumn>,
        autogeneratedKey: QueryColumn?
    ): InsertGeneratorResult {
        val arguments = Arguments(allocator)

        val values = columns.joinToString(
            separator = ", ",
            transform = {
                when {
                    it.type.isEnum -> "CAST(:${arguments.createArgument(COLUMN, it.name)} AS ${it.dbType})"
                    else -> ":${arguments.createArgument(COLUMN, it.name)}"
                }
            }
        )

        return InsertGeneratorResult(
            updateResult = GeneratorResult(
                query =
                multiline(
                    """
                        INSERT INTO ${tableName.toQuoted()} 
                        (${columns.joinToString(separator = ", ") { it.name.toQuoted() }}) 
                        VALUES ($values)
                    """
                ),
                arguments = arguments
            )
        )
    }

    override fun createUpdateQuery(
        allocator: ParameterAllocator,
        tableName: String,
        argumentColumns: List<QueryColumn>,
        expressionColumns: ExpressionColumns,
        where: String?
    ): GeneratorResult {
        val arguments = Arguments(allocator)

        val values = argumentColumns.joinToString(
            separator = ", ",
            transform = {
                it.name.toQuoted() + " = " + when {
                    it.type.isEnum -> "CAST(:${arguments.createArgument(COLUMN, it.name)} AS ${it.dbType})"
                    else -> ":${arguments.createArgument(COLUMN, it.name)}"
                }
            }
        )

        return GeneratorResult(
            query =
            multiline("""
                    UPDATE ${tableName.toQuoted()} 
                    SET ${listOf(values, expressionColumns.toUpdateValues()).filter { it.isNotBlank() }.joinToString(separator = ", ")}
                    ${where?.let { "WHERE $it" } ?: ""}
                """),
            arguments = arguments
        )
    }

}