package com.dzikoysk.sqiffy.dsl.generator.dialects

import com.dzikoysk.sqiffy.dsl.Column
import com.dzikoysk.sqiffy.dsl.generator.ArgumentType.COLUMN
import com.dzikoysk.sqiffy.dsl.generator.Arguments
import com.dzikoysk.sqiffy.dsl.generator.ParameterAllocator
import com.dzikoysk.sqiffy.dsl.generator.QueryColumn
import com.dzikoysk.sqiffy.dsl.generator.SqlQueryGenerator.GeneratorResult
import com.dzikoysk.sqiffy.dsl.generator.SqlQueryGenerator.InsertGeneratorResult
import com.dzikoysk.sqiffy.shared.multiline

object SqliteQueryGenerator : GenericMySqlQueryGenerator(autogeneratedKeyAsNull = true) {

    override fun createInsertOrIgnoreQuery(
        allocator: ParameterAllocator,
        tableName: String,
        columns: List<QueryColumn>,
        conflictingColumns: Collection<Column<*>>,
    ): GeneratorResult {
        val arguments = Arguments(allocator)

        val values = columns.joinToString(
            separator = ", ",
            transform = { ":${arguments.createArgument(COLUMN, it.name)}" }
        )

        return GeneratorResult(
            query =
                multiline("""
                    INSERT OR IGNORE INTO ${tableName.toQuoted()}
                    (${columns.joinToString(separator = ", ") { it.name.toQuoted() }})
                    VALUES ($values)
                """),
            arguments = arguments
        )
    }

    override fun createInsertQuery(
        allocator: ParameterAllocator,
        tableName: String,
        columns: List<QueryColumn>,
        autogeneratedKey: QueryColumn?
    ): InsertGeneratorResult {
        val baseQuery = super.createInsertQuery(allocator, tableName, columns, autogeneratedKey)

        if (autogeneratedKey != null) {
            return InsertGeneratorResult(
                updateResult = baseQuery.updateResult,
                customSelectForAutogeneratedKey = """
                    SELECT ${autogeneratedKey.name.toQuoted()} AS ${"$tableName.${autogeneratedKey.name}".toQuoted()} 
                    FROM ${tableName.toQuoted()} 
                    WHERE rowid = last_insert_rowid();
                """.trimIndent()
            )
        }

        return baseQuery
    }

}