package com.dzikoysk.sqiffy.dsl.generator.dialects

import com.dzikoysk.sqiffy.dsl.generator.ParameterAllocator
import com.dzikoysk.sqiffy.dsl.generator.QueryColumn
import com.dzikoysk.sqiffy.dsl.generator.SqlQueryGenerator.InsertGeneratorResult

object SqliteQueryGenerator : GenericMySqlQueryGenerator(autogeneratedKeyAsNull = true) {

    override fun createInsertQuery(
        allocator: ParameterAllocator,
        tableName: String,
        columns: List<QueryColumn>,
        autogeneratedKey: QueryColumn?
    ): InsertGeneratorResult {
        val baseQuery = super.createInsertQuery(allocator, tableName, columns, autogeneratedKey)

        if (autogeneratedKey != null) {
            return InsertGeneratorResult(
                updateResult = baseQuery.updateResult,
                customSelectForAutogeneratedKey = """
                    SELECT ${autogeneratedKey.name.toQuoted()} AS ${"$tableName.${autogeneratedKey.name}".toQuoted()} 
                    FROM ${tableName.toQuoted()} 
                    WHERE rowid = last_insert_rowid();
                """.trimIndent()
            )
        }

        return baseQuery
    }

}